AWSTemplateFormatVersion: '2010-09-09'
Description: 'Crear un plan de backup automatico con parametros'
Metadata:
  Version: 1.0
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'Opciones iniciales de backup'
        Parameters:
          - BackupPlanName
          - BackupVaultName
          - KMSArn
          - BackupSelectionName
          - BackupTag
      - Label:
          default: 'Configurar reglas de backup'
        Parameters:
          - RuleName1
          - BackupFrecuency1
          - MoveToColdStorageAfterDays1
          - RuleName2
          - BackupFrecuency2
          - MoveToColdStorageAfterDays2
          - RuleName3
          - BackupFrecuency3
          - MoveToColdStorageAfterDays3
      - Label:
          default: "Creacion de rol de backup"
        Parameters:
          - BackupRoleName
Parameters:
  StackNumber:
    Description: 'Use to avoid conflicts when deploy various instances of this instance with the same name; <prefix>-[00 | 01 | 02 | ...]-<name>'
    Type: String
    Default: '00'
  MasterBaseStack:
    Description: Stack name of base stack.
    Type: String
    Default: 'LPSTV-0001-DVSC-SCP-ST-00-MASTER-BASE'
  BackupPlanName:
    Type: String
    Description: 'Asigne un nombre al plan de copia de seguridad'
    Default: 'plan'
  BackupVaultName:
    Type: String
    Description: 'Especifica un almacen de copia de seguridad'
    Default: 'vault'
  BackupSelectionName:
    Type: String
    Description: 'Especifica un objeto para el plan de copia de seguridad'
    Default: 'selection'
  BackupTagKey:
    Type: String
    Description: "Especifique un nombre para la etiqueta backup"
    Default: "BACKUP"
  BackupTagValue:
    Type: String
    Description: "Especifique un valor para la etiqueta backup"
    Default: "YES"
  RuleName1:
    Type: String
    Description: 'Asigne un nombre de regla de backup'
    Default: 'TestRule1'
  BackupFrecuency1:
    Type: String
    Description: 'Utilice una expresion cron para programar la copia de seguridad'
    Default: 'cron(0 5 ? * * *)'
  MoveToColdStorageAfterDays1:
    Type: Number
    Description: 'Especifique el numero de dias para transferir la copia de seguridad al almacenamiento en frío'
    Default: 120
  RuleName2:
    Type: String
    Description: 'Asigne un nombre de regla de backup'
    Default: 'TestRule2'
  BackupFrecuency2:
    Type: String
    Description: 'Utilice una expresion cron para programar la copia de seguridad'
    Default: 'cron(0 5 ? * SUN *)'
  MoveToColdStorageAfterDays2:
    Type: Number
    Description: 'Especifique el numero de dias para transferir la copia de seguridad al almacenamiento en frío'
    Default: 120
  RuleName3:
    Type: String
    Description: 'Asigne un nombre de regla de backup'
    Default: 'TestRule3'
  BackupFrecuency3:
    Type: String
    Description: 'Utilice una expresion cron para programar la copia de seguridad'
    Default: 'cron(0 5 1 * ? *)'
  MoveToColdStorageAfterDays3:
    Type: Number
    Description: 'Especifique el numero de dias para transferir la copia de seguridad al almacenamiento en frío'
    Default: 120
  BackupRoleName:
    Type: String
    Description: 'Asigne un nombre al rol de copia de seguridad'
    Default: 'role'
Resources:
  BackupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../lib/templates/backup/backup.yaml
      Parameters:
        StackNumber: !Ref StackNumber
        EnvironmentStack: !ImportValue
          'Fn::Sub': '${MasterBaseStack}-EnvironmentStack'
        KmsStack: !ImportValue
          'Fn::Sub': '${MasterBaseStack}-KmsStack'
        BackupPlanName: !Ref BackupPlanName
        BackupVaultName: !Ref BackupVaultName
        BackupSelectionName: !Ref BackupSelectionName
        BackupTagKey: !Ref BackupTagKey
        BackupTagValue: !Ref BackupTagValue
        RuleName1: !Ref RuleName1
        BackupFrecuency1: !Ref BackupFrecuency1
        MoveToColdStorageAfterDays1: !Ref MoveToColdStorageAfterDays1
        RuleName2: !Ref RuleName2
        BackupFrecuency2: !Ref BackupFrecuency2
        MoveToColdStorageAfterDays2: !Ref MoveToColdStorageAfterDays2
        RuleName3: !Ref RuleName3
        BackupFrecuency3: !Ref BackupFrecuency3
        MoveToColdStorageAfterDays3: !Ref MoveToColdStorageAfterDays3
        BackupRoleName: !Ref BackupRoleName
